// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TempLoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TempLoginReq) Reset()         { *m = TempLoginReq{} }
func (m *TempLoginReq) String() string { return proto.CompactTextString(m) }
func (*TempLoginReq) ProtoMessage()    {}
func (*TempLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *TempLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TempLoginReq.Unmarshal(m, b)
}
func (m *TempLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TempLoginReq.Marshal(b, m, deterministic)
}
func (m *TempLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TempLoginReq.Merge(m, src)
}
func (m *TempLoginReq) XXX_Size() int {
	return xxx_messageInfo_TempLoginReq.Size(m)
}
func (m *TempLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TempLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_TempLoginReq proto.InternalMessageInfo

func (m *TempLoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TempLoginRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TempLoginRes) Reset()         { *m = TempLoginRes{} }
func (m *TempLoginRes) String() string { return proto.CompactTextString(m) }
func (*TempLoginRes) ProtoMessage()    {}
func (*TempLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *TempLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TempLoginRes.Unmarshal(m, b)
}
func (m *TempLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TempLoginRes.Marshal(b, m, deterministic)
}
func (m *TempLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TempLoginRes.Merge(m, src)
}
func (m *TempLoginRes) XXX_Size() int {
	return xxx_messageInfo_TempLoginRes.Size(m)
}
func (m *TempLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TempLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_TempLoginRes proto.InternalMessageInfo

func (m *TempLoginRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TempLoginRes) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*TempLoginReq)(nil), "protos.TempLoginReq")
	proto.RegisterType((*TempLoginRes)(nil), "protos.TempLoginRes")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x4a, 0x5c, 0x3c,
	0x21, 0xa9, 0xb9, 0x05, 0x3e, 0x20, 0xa9, 0xa0, 0xd4, 0x42, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4,
	0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc9, 0x09, 0x45, 0x4d, 0xb1,
	0x90, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0x31, 0x54, 0x15, 0x94, 0x27, 0x24, 0xc5,
	0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x04, 0xd6, 0xcf, 0x04, 0x96, 0x81, 0xf3, 0x93, 0x20, 0xf6, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x02, 0xe7, 0xaa, 0x5e, 0x85, 0x00, 0x00, 0x00,
}
