// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HeroName             string   `protobuf:"bytes,2,opt,name=hero_name,json=heroName,proto3" json:"hero_name,omitempty"`
	HeroHp               uint32   `protobuf:"varint,3,opt,name=hero_hp,json=heroHp,proto3" json:"hero_hp,omitempty"`
	Fv                   uint32   `protobuf:"varint,4,opt,name=fv,proto3" json:"fv,omitempty"`
	Belief               uint32   `protobuf:"varint,5,opt,name=belief,proto3" json:"belief,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PlayerInfo) GetHeroName() string {
	if m != nil {
		return m.HeroName
	}
	return ""
}

func (m *PlayerInfo) GetHeroHp() uint32 {
	if m != nil {
		return m.HeroHp
	}
	return 0
}

func (m *PlayerInfo) GetFv() uint32 {
	if m != nil {
		return m.Fv
	}
	return 0
}

func (m *PlayerInfo) GetBelief() uint32 {
	if m != nil {
		return m.Belief
	}
	return 0
}

type RoomIdentify struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RoomId               uint32   `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomIdentify) Reset()         { *m = RoomIdentify{} }
func (m *RoomIdentify) String() string { return proto.CompactTextString(m) }
func (*RoomIdentify) ProtoMessage()    {}
func (*RoomIdentify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *RoomIdentify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomIdentify.Unmarshal(m, b)
}
func (m *RoomIdentify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomIdentify.Marshal(b, m, deterministic)
}
func (m *RoomIdentify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomIdentify.Merge(m, src)
}
func (m *RoomIdentify) XXX_Size() int {
	return xxx_messageInfo_RoomIdentify.Size(m)
}
func (m *RoomIdentify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomIdentify.DiscardUnknown(m)
}

var xxx_messageInfo_RoomIdentify proto.InternalMessageInfo

func (m *RoomIdentify) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RoomIdentify) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type CreateRoomReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HeroId               uint32   `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Pve                  bool     `protobuf:"varint,3,opt,name=pve,proto3" json:"pve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(m, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

func (m *CreateRoomReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRoomReq) GetHeroId() uint32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *CreateRoomReq) GetPve() bool {
	if m != nil {
		return m.Pve
	}
	return false
}

type CreateRoomRes struct {
	RoomId               uint32      `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	P1                   *PlayerInfo `protobuf:"bytes,2,opt,name=p1,proto3" json:"p1,omitempty"`
	P2                   *PlayerInfo `protobuf:"bytes,3,opt,name=p2,proto3" json:"p2,omitempty"`
	IsCreate             bool        `protobuf:"varint,4,opt,name=is_create,json=isCreate,proto3" json:"is_create,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRoomRes) Reset()         { *m = CreateRoomRes{} }
func (m *CreateRoomRes) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRes) ProtoMessage()    {}
func (*CreateRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *CreateRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRes.Unmarshal(m, b)
}
func (m *CreateRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRes.Marshal(b, m, deterministic)
}
func (m *CreateRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRes.Merge(m, src)
}
func (m *CreateRoomRes) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRes.Size(m)
}
func (m *CreateRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRes proto.InternalMessageInfo

func (m *CreateRoomRes) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateRoomRes) GetP1() *PlayerInfo {
	if m != nil {
		return m.P1
	}
	return nil
}

func (m *CreateRoomRes) GetP2() *PlayerInfo {
	if m != nil {
		return m.P2
	}
	return nil
}

func (m *CreateRoomRes) GetIsCreate() bool {
	if m != nil {
		return m.IsCreate
	}
	return false
}

type RoomReadyReq struct {
	RoomIde              *RoomIdentify `protobuf:"bytes,1,opt,name=room_ide,json=roomIde,proto3" json:"room_ide,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomReadyReq) Reset()         { *m = RoomReadyReq{} }
func (m *RoomReadyReq) String() string { return proto.CompactTextString(m) }
func (*RoomReadyReq) ProtoMessage()    {}
func (*RoomReadyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}

func (m *RoomReadyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReadyReq.Unmarshal(m, b)
}
func (m *RoomReadyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReadyReq.Marshal(b, m, deterministic)
}
func (m *RoomReadyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReadyReq.Merge(m, src)
}
func (m *RoomReadyReq) XXX_Size() int {
	return xxx_messageInfo_RoomReadyReq.Size(m)
}
func (m *RoomReadyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReadyReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReadyReq proto.InternalMessageInfo

func (m *RoomReadyReq) GetRoomIde() *RoomIdentify {
	if m != nil {
		return m.RoomIde
	}
	return nil
}

type RoomReadyRes struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReadyRes) Reset()         { *m = RoomReadyRes{} }
func (m *RoomReadyRes) String() string { return proto.CompactTextString(m) }
func (*RoomReadyRes) ProtoMessage()    {}
func (*RoomReadyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{5}
}

func (m *RoomReadyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReadyRes.Unmarshal(m, b)
}
func (m *RoomReadyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReadyRes.Marshal(b, m, deterministic)
}
func (m *RoomReadyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReadyRes.Merge(m, src)
}
func (m *RoomReadyRes) XXX_Size() int {
	return xxx_messageInfo_RoomReadyRes.Size(m)
}
func (m *RoomReadyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReadyRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReadyRes proto.InternalMessageInfo

func (m *RoomReadyRes) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type NotifyRefreshCenterShop struct {
	CenterShopCards      []string `protobuf:"bytes,1,rep,name=center_shop_cards,json=centerShopCards,proto3" json:"center_shop_cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRefreshCenterShop) Reset()         { *m = NotifyRefreshCenterShop{} }
func (m *NotifyRefreshCenterShop) String() string { return proto.CompactTextString(m) }
func (*NotifyRefreshCenterShop) ProtoMessage()    {}
func (*NotifyRefreshCenterShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{6}
}

func (m *NotifyRefreshCenterShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRefreshCenterShop.Unmarshal(m, b)
}
func (m *NotifyRefreshCenterShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRefreshCenterShop.Marshal(b, m, deterministic)
}
func (m *NotifyRefreshCenterShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRefreshCenterShop.Merge(m, src)
}
func (m *NotifyRefreshCenterShop) XXX_Size() int {
	return xxx_messageInfo_NotifyRefreshCenterShop.Size(m)
}
func (m *NotifyRefreshCenterShop) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRefreshCenterShop.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRefreshCenterShop proto.InternalMessageInfo

func (m *NotifyRefreshCenterShop) GetCenterShopCards() []string {
	if m != nil {
		return m.CenterShopCards
	}
	return nil
}

type RenderCenterShopEnd struct {
	RoomIde              *RoomIdentify `protobuf:"bytes,1,opt,name=room_ide,json=roomIde,proto3" json:"room_ide,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RenderCenterShopEnd) Reset()         { *m = RenderCenterShopEnd{} }
func (m *RenderCenterShopEnd) String() string { return proto.CompactTextString(m) }
func (*RenderCenterShopEnd) ProtoMessage()    {}
func (*RenderCenterShopEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{7}
}

func (m *RenderCenterShopEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderCenterShopEnd.Unmarshal(m, b)
}
func (m *RenderCenterShopEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderCenterShopEnd.Marshal(b, m, deterministic)
}
func (m *RenderCenterShopEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderCenterShopEnd.Merge(m, src)
}
func (m *RenderCenterShopEnd) XXX_Size() int {
	return xxx_messageInfo_RenderCenterShopEnd.Size(m)
}
func (m *RenderCenterShopEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderCenterShopEnd.DiscardUnknown(m)
}

var xxx_messageInfo_RenderCenterShopEnd proto.InternalMessageInfo

func (m *RenderCenterShopEnd) GetRoomIde() *RoomIdentify {
	if m != nil {
		return m.RoomIde
	}
	return nil
}

type NotifyLotteryHandCards struct {
	Cards                []string `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	OppCardCount         uint32   `protobuf:"varint,2,opt,name=opp_card_count,json=oppCardCount,proto3" json:"opp_card_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyLotteryHandCards) Reset()         { *m = NotifyLotteryHandCards{} }
func (m *NotifyLotteryHandCards) String() string { return proto.CompactTextString(m) }
func (*NotifyLotteryHandCards) ProtoMessage()    {}
func (*NotifyLotteryHandCards) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{8}
}

func (m *NotifyLotteryHandCards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyLotteryHandCards.Unmarshal(m, b)
}
func (m *NotifyLotteryHandCards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyLotteryHandCards.Marshal(b, m, deterministic)
}
func (m *NotifyLotteryHandCards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyLotteryHandCards.Merge(m, src)
}
func (m *NotifyLotteryHandCards) XXX_Size() int {
	return xxx_messageInfo_NotifyLotteryHandCards.Size(m)
}
func (m *NotifyLotteryHandCards) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyLotteryHandCards.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyLotteryHandCards proto.InternalMessageInfo

func (m *NotifyLotteryHandCards) GetCards() []string {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *NotifyLotteryHandCards) GetOppCardCount() uint32 {
	if m != nil {
		return m.OppCardCount
	}
	return 0
}

type RenderLotteryHandCardsEnd struct {
	RoomIde              *RoomIdentify `protobuf:"bytes,1,opt,name=room_ide,json=roomIde,proto3" json:"room_ide,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RenderLotteryHandCardsEnd) Reset()         { *m = RenderLotteryHandCardsEnd{} }
func (m *RenderLotteryHandCardsEnd) String() string { return proto.CompactTextString(m) }
func (*RenderLotteryHandCardsEnd) ProtoMessage()    {}
func (*RenderLotteryHandCardsEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{9}
}

func (m *RenderLotteryHandCardsEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderLotteryHandCardsEnd.Unmarshal(m, b)
}
func (m *RenderLotteryHandCardsEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderLotteryHandCardsEnd.Marshal(b, m, deterministic)
}
func (m *RenderLotteryHandCardsEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderLotteryHandCardsEnd.Merge(m, src)
}
func (m *RenderLotteryHandCardsEnd) XXX_Size() int {
	return xxx_messageInfo_RenderLotteryHandCardsEnd.Size(m)
}
func (m *RenderLotteryHandCardsEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderLotteryHandCardsEnd.DiscardUnknown(m)
}

var xxx_messageInfo_RenderLotteryHandCardsEnd proto.InternalMessageInfo

func (m *RenderLotteryHandCardsEnd) GetRoomIde() *RoomIdentify {
	if m != nil {
		return m.RoomIde
	}
	return nil
}

type NotifyPlayerRoomInfo struct {
	CenterShopCards      []string `protobuf:"bytes,1,rep,name=center_shop_cards,json=centerShopCards,proto3" json:"center_shop_cards,omitempty"`
	PlayerHandCards      []string `protobuf:"bytes,2,rep,name=player_hand_cards,json=playerHandCards,proto3" json:"player_hand_cards,omitempty"`
	CurTurnUser          string   `protobuf:"bytes,3,opt,name=cur_turn_user,json=curTurnUser,proto3" json:"cur_turn_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyPlayerRoomInfo) Reset()         { *m = NotifyPlayerRoomInfo{} }
func (m *NotifyPlayerRoomInfo) String() string { return proto.CompactTextString(m) }
func (*NotifyPlayerRoomInfo) ProtoMessage()    {}
func (*NotifyPlayerRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{10}
}

func (m *NotifyPlayerRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPlayerRoomInfo.Unmarshal(m, b)
}
func (m *NotifyPlayerRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPlayerRoomInfo.Marshal(b, m, deterministic)
}
func (m *NotifyPlayerRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPlayerRoomInfo.Merge(m, src)
}
func (m *NotifyPlayerRoomInfo) XXX_Size() int {
	return xxx_messageInfo_NotifyPlayerRoomInfo.Size(m)
}
func (m *NotifyPlayerRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPlayerRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPlayerRoomInfo proto.InternalMessageInfo

func (m *NotifyPlayerRoomInfo) GetCenterShopCards() []string {
	if m != nil {
		return m.CenterShopCards
	}
	return nil
}

func (m *NotifyPlayerRoomInfo) GetPlayerHandCards() []string {
	if m != nil {
		return m.PlayerHandCards
	}
	return nil
}

func (m *NotifyPlayerRoomInfo) GetCurTurnUser() string {
	if m != nil {
		return m.CurTurnUser
	}
	return ""
}

type JoinRoomReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RoomId               uint32   `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	HeroId               string   `protobuf:"bytes,3,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{11}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

func (m *JoinRoomReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *JoinRoomReq) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomReq) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

type JoinRoomRes struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRes) Reset()         { *m = JoinRoomRes{} }
func (m *JoinRoomRes) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRes) ProtoMessage()    {}
func (*JoinRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{12}
}

func (m *JoinRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRes.Unmarshal(m, b)
}
func (m *JoinRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRes.Marshal(b, m, deterministic)
}
func (m *JoinRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRes.Merge(m, src)
}
func (m *JoinRoomRes) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRes.Size(m)
}
func (m *JoinRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRes proto.InternalMessageInfo

func (m *JoinRoomRes) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerInfo)(nil), "protos.PlayerInfo")
	proto.RegisterType((*RoomIdentify)(nil), "protos.RoomIdentify")
	proto.RegisterType((*CreateRoomReq)(nil), "protos.CreateRoomReq")
	proto.RegisterType((*CreateRoomRes)(nil), "protos.CreateRoomRes")
	proto.RegisterType((*RoomReadyReq)(nil), "protos.RoomReadyReq")
	proto.RegisterType((*RoomReadyRes)(nil), "protos.RoomReadyRes")
	proto.RegisterType((*NotifyRefreshCenterShop)(nil), "protos.NotifyRefreshCenterShop")
	proto.RegisterType((*RenderCenterShopEnd)(nil), "protos.RenderCenterShopEnd")
	proto.RegisterType((*NotifyLotteryHandCards)(nil), "protos.NotifyLotteryHandCards")
	proto.RegisterType((*RenderLotteryHandCardsEnd)(nil), "protos.RenderLotteryHandCardsEnd")
	proto.RegisterType((*NotifyPlayerRoomInfo)(nil), "protos.NotifyPlayerRoomInfo")
	proto.RegisterType((*JoinRoomReq)(nil), "protos.JoinRoomReq")
	proto.RegisterType((*JoinRoomRes)(nil), "protos.JoinRoomRes")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x87, 0xe6, 0xcf, 0xa4, 0x29, 0xb0, 0x44, 0x8d, 0x81, 0x4b, 0xb4, 0x02, 0x14,
	0x71, 0x28, 0x6a, 0x78, 0x00, 0x0e, 0x56, 0x51, 0x83, 0xaa, 0x0a, 0x2d, 0x85, 0x0b, 0x07, 0xcb,
	0xb5, 0xc7, 0xb2, 0xa5, 0x64, 0x77, 0xd9, 0xb5, 0x23, 0xe5, 0x05, 0xb8, 0x71, 0xe1, 0x89, 0xd1,
	0xce, 0x86, 0xc4, 0x45, 0x14, 0x28, 0xa7, 0x64, 0x76, 0xbe, 0xfd, 0xf6, 0x37, 0xb3, 0x3b, 0x06,
	0x30, 0x4a, 0xad, 0x4e, 0xb4, 0x51, 0xb5, 0x62, 0x5d, 0xfa, 0xb1, 0xfc, 0x6b, 0x00, 0xf0, 0x7e,
	0x99, 0x6e, 0xd0, 0x2c, 0x64, 0xa1, 0xd8, 0x13, 0xe8, 0x37, 0x16, 0x8d, 0x4c, 0x57, 0x18, 0x05,
	0xd3, 0x60, 0x36, 0x10, 0xbb, 0x98, 0x3d, 0x85, 0x41, 0x89, 0x46, 0x25, 0x94, 0x0c, 0x7d, 0xd2,
	0x2d, 0x5c, 0xba, 0xe4, 0x04, 0x7a, 0x94, 0x2c, 0x75, 0xd4, 0x99, 0x06, 0xb3, 0x91, 0xe8, 0xba,
	0xf0, 0x5c, 0xb3, 0x23, 0x08, 0x8b, 0x75, 0x74, 0x8f, 0xd6, 0xc2, 0x62, 0xcd, 0x8e, 0xa1, 0x7b,
	0x8d, 0xcb, 0x0a, 0x8b, 0xe8, 0xc0, 0xeb, 0x7c, 0xc4, 0x63, 0x38, 0x14, 0x4a, 0xad, 0x16, 0x39,
	0xca, 0xba, 0x2a, 0x36, 0x7f, 0x24, 0x99, 0x40, 0xcf, 0x95, 0x92, 0x54, 0x39, 0x71, 0x8c, 0x44,
	0xd7, 0xd0, 0x56, 0xfe, 0x09, 0x46, 0xb1, 0xc1, 0xb4, 0x46, 0x67, 0x25, 0xf0, 0xcb, 0xdf, 0x5c,
	0x08, 0x79, 0xef, 0xe2, 0xc2, 0x45, 0xce, 0x1e, 0x40, 0x47, 0xaf, 0x91, 0xea, 0xe8, 0x0b, 0xf7,
	0x97, 0x7f, 0x0b, 0x6e, 0x1a, 0xdb, 0x36, 0x42, 0xd0, 0x46, 0x60, 0x1c, 0x42, 0x7d, 0x4a, 0x86,
	0xc3, 0x39, 0xf3, 0xcd, 0xb6, 0x27, 0xfb, 0x0e, 0x8b, 0x50, 0x9f, 0x92, 0x66, 0x4e, 0xfe, 0xb7,
	0x69, 0xe6, 0xae, 0xdb, 0x95, 0x4d, 0x32, 0x3a, 0x94, 0xda, 0xd7, 0x17, 0xfd, 0xca, 0x7a, 0x08,
	0xfe, 0xc6, 0x37, 0x4b, 0x60, 0x9a, 0x6f, 0x5c, 0x99, 0xaf, 0xa0, 0xbf, 0xa5, 0xf1, 0x65, 0x0e,
	0xe7, 0xe3, 0x9f, 0xb6, 0xed, 0xa6, 0x8a, 0x9e, 0x87, 0x44, 0xfe, 0xe2, 0x86, 0x81, 0x75, 0xb7,
	0x62, 0xd0, 0x36, 0xcb, 0x7a, 0x57, 0x0d, 0x45, 0xfc, 0x0c, 0x26, 0x97, 0x8a, 0xb6, 0x62, 0x61,
	0xd0, 0x96, 0x31, 0xca, 0x1a, 0xcd, 0x87, 0x52, 0x69, 0xf6, 0x12, 0x1e, 0x66, 0x14, 0x25, 0xb6,
	0x54, 0x3a, 0xc9, 0x52, 0x93, 0xdb, 0x28, 0x98, 0x76, 0x66, 0x03, 0x71, 0x3f, 0xdb, 0xc9, 0x62,
	0xb7, 0xcc, 0xdf, 0xc2, 0x23, 0x81, 0x32, 0x47, 0xb3, 0xdf, 0x7f, 0x26, 0xf3, 0xbb, 0x63, 0x5f,
	0xc1, 0xb1, 0xc7, 0xb9, 0x50, 0x75, 0x8d, 0x66, 0x73, 0x9e, 0xca, 0x9c, 0x4e, 0x60, 0x63, 0x38,
	0x68, 0x13, 0xf8, 0x80, 0x3d, 0x83, 0x23, 0xa5, 0x3d, 0x5b, 0x92, 0xa9, 0x46, 0xd6, 0xdb, 0x9b,
	0x3e, 0x54, 0x9a, 0xc8, 0x62, 0xb7, 0xc6, 0x2f, 0xe0, 0xb1, 0xa7, 0xfb, 0xd5, 0xf5, 0xbf, 0x18,
	0xbf, 0x07, 0x30, 0xf6, 0x90, 0xfe, 0x46, 0x49, 0xe5, 0x66, 0xeb, 0x0e, 0x0d, 0x73, 0x5a, 0x4d,
	0xbb, 0x93, 0x32, 0x95, 0xf9, 0x56, 0x1b, 0x7a, 0xad, 0x4f, 0xec, 0x4b, 0xe7, 0x30, 0xca, 0x1a,
	0x93, 0xd4, 0x8d, 0x91, 0x89, 0x7b, 0xdc, 0xf4, 0xb0, 0x06, 0x62, 0x98, 0x35, 0xe6, 0xaa, 0x31,
	0xf2, 0xa3, 0x45, 0xc3, 0x3f, 0xc3, 0xf0, 0x9d, 0xaa, 0xe4, 0x3f, 0x8e, 0xc5, 0x6f, 0x87, 0xab,
	0x3d, 0x2f, 0xfe, 0x84, 0xed, 0xbc, 0xf0, 0xe7, 0x6d, 0xf3, 0x5b, 0xdf, 0xd2, 0xb5, 0xff, 0xe4,
	0xbc, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0x63, 0xc4, 0xcf, 0x7d, 0x87, 0x04, 0x00, 0x00,
}
